// This file is auto-generated by scripts/generate_structure_boundaries.js
// Do not edit manually.

export interface VerseRef {
    surah: number;
    ayah: number;
}

export interface StructureBoundary {
    start: VerseRef;
    end: VerseRef;
}

export const JUZ_BOUNDARIES: (StructureBoundary | null)[] = [
    {
        "start": {
            "surah": 1,
            "ayah": 1
        },
        "end": {
            "surah": 2,
            "ayah": 141
        }
    },
    {
        "start": {
            "surah": 2,
            "ayah": 142
        },
        "end": {
            "surah": 2,
            "ayah": 252
        }
    },
    {
        "start": {
            "surah": 2,
            "ayah": 253
        },
        "end": {
            "surah": 3,
            "ayah": 100
        }
    },
    {
        "start": {
            "surah": 3,
            "ayah": 101
        },
        "end": {
            "surah": 4,
            "ayah": 23
        }
    },
    {
        "start": {
            "surah": 4,
            "ayah": 24
        },
        "end": {
            "surah": 4,
            "ayah": 147
        }
    },
    {
        "start": {
            "surah": 4,
            "ayah": 148
        },
        "end": {
            "surah": 5,
            "ayah": 82
        }
    },
    {
        "start": {
            "surah": 5,
            "ayah": 83
        },
        "end": {
            "surah": 6,
            "ayah": 110
        }
    },
    {
        "start": {
            "surah": 6,
            "ayah": 111
        },
        "end": {
            "surah": 7,
            "ayah": 87
        }
    },
    {
        "start": {
            "surah": 7,
            "ayah": 88
        },
        "end": {
            "surah": 8,
            "ayah": 40
        }
    },
    {
        "start": {
            "surah": 8,
            "ayah": 41
        },
        "end": {
            "surah": 9,
            "ayah": 93
        }
    },
    {
        "start": {
            "surah": 9,
            "ayah": 94
        },
        "end": {
            "surah": 11,
            "ayah": 5
        }
    },
    {
        "start": {
            "surah": 11,
            "ayah": 6
        },
        "end": {
            "surah": 12,
            "ayah": 52
        }
    },
    {
        "start": {
            "surah": 12,
            "ayah": 53
        },
        "end": {
            "surah": 14,
            "ayah": 52
        }
    },
    {
        "start": {
            "surah": 15,
            "ayah": 1
        },
        "end": {
            "surah": 16,
            "ayah": 128
        }
    },
    {
        "start": {
            "surah": 17,
            "ayah": 1
        },
        "end": {
            "surah": 18,
            "ayah": 74
        }
    },
    {
        "start": {
            "surah": 18,
            "ayah": 75
        },
        "end": {
            "surah": 20,
            "ayah": 135
        }
    },
    {
        "start": {
            "surah": 21,
            "ayah": 1
        },
        "end": {
            "surah": 22,
            "ayah": 78
        }
    },
    {
        "start": {
            "surah": 23,
            "ayah": 1
        },
        "end": {
            "surah": 25,
            "ayah": 20
        }
    },
    {
        "start": {
            "surah": 25,
            "ayah": 21
        },
        "end": {
            "surah": 27,
            "ayah": 55
        }
    },
    {
        "start": {
            "surah": 27,
            "ayah": 56
        },
        "end": {
            "surah": 29,
            "ayah": 45
        }
    },
    {
        "start": {
            "surah": 29,
            "ayah": 46
        },
        "end": {
            "surah": 33,
            "ayah": 30
        }
    },
    {
        "start": {
            "surah": 33,
            "ayah": 31
        },
        "end": {
            "surah": 36,
            "ayah": 27
        }
    },
    {
        "start": {
            "surah": 36,
            "ayah": 28
        },
        "end": {
            "surah": 39,
            "ayah": 31
        }
    },
    {
        "start": {
            "surah": 39,
            "ayah": 32
        },
        "end": {
            "surah": 41,
            "ayah": 46
        }
    },
    {
        "start": {
            "surah": 41,
            "ayah": 47
        },
        "end": {
            "surah": 46,
            "ayah": 5
        }
    },
    {
        "start": {
            "surah": 46,
            "ayah": 6
        },
        "end": {
            "surah": 51,
            "ayah": 30
        }
    },
    {
        "start": {
            "surah": 51,
            "ayah": 31
        },
        "end": {
            "surah": 57,
            "ayah": 29
        }
    },
    {
        "start": {
            "surah": 58,
            "ayah": 1
        },
        "end": {
            "surah": 66,
            "ayah": 12
        }
    },
    {
        "start": {
            "surah": 67,
            "ayah": 1
        },
        "end": {
            "surah": 77,
            "ayah": 50
        }
    },
    {
        "start": {
            "surah": 78,
            "ayah": 1
        },
        "end": {
            "surah": 114,
            "ayah": 6
        }
    }
];

export const HIZB_BOUNDARIES: (StructureBoundary | null)[] = [
    {
        "start": {
            "surah": 1,
            "ayah": 1
        },
        "end": {
            "surah": 2,
            "ayah": 76
        }
    },
    {
        "start": {
            "surah": 2,
            "ayah": 77
        },
        "end": {
            "surah": 2,
            "ayah": 141
        }
    },
    {
        "start": {
            "surah": 2,
            "ayah": 142
        },
        "end": {
            "surah": 2,
            "ayah": 202
        }
    },
    {
        "start": {
            "surah": 2,
            "ayah": 203
        },
        "end": {
            "surah": 2,
            "ayah": 252
        }
    },
    {
        "start": {
            "surah": 2,
            "ayah": 253
        },
        "end": {
            "surah": 3,
            "ayah": 15
        }
    },
    {
        "start": {
            "surah": 3,
            "ayah": 16
        },
        "end": {
            "surah": 3,
            "ayah": 100
        }
    },
    {
        "start": {
            "surah": 3,
            "ayah": 101
        },
        "end": {
            "surah": 3,
            "ayah": 173
        }
    },
    {
        "start": {
            "surah": 3,
            "ayah": 174
        },
        "end": {
            "surah": 4,
            "ayah": 23
        }
    },
    {
        "start": {
            "surah": 4,
            "ayah": 24
        },
        "end": {
            "surah": 4,
            "ayah": 91
        }
    },
    {
        "start": {
            "surah": 4,
            "ayah": 92
        },
        "end": {
            "surah": 4,
            "ayah": 147
        }
    },
    {
        "start": {
            "surah": 4,
            "ayah": 148
        },
        "end": {
            "surah": 5,
            "ayah": 31
        }
    },
    {
        "start": {
            "surah": 5,
            "ayah": 32
        },
        "end": {
            "surah": 5,
            "ayah": 82
        }
    },
    {
        "start": {
            "surah": 5,
            "ayah": 83
        },
        "end": {
            "surah": 6,
            "ayah": 35
        }
    },
    {
        "start": {
            "surah": 6,
            "ayah": 36
        },
        "end": {
            "surah": 6,
            "ayah": 110
        }
    },
    {
        "start": {
            "surah": 6,
            "ayah": 111
        },
        "end": {
            "surah": 6,
            "ayah": 165
        }
    },
    {
        "start": {
            "surah": 7,
            "ayah": 1
        },
        "end": {
            "surah": 7,
            "ayah": 87
        }
    },
    {
        "start": {
            "surah": 7,
            "ayah": 88
        },
        "end": {
            "surah": 7,
            "ayah": 170
        }
    },
    {
        "start": {
            "surah": 7,
            "ayah": 171
        },
        "end": {
            "surah": 8,
            "ayah": 40
        }
    },
    {
        "start": {
            "surah": 8,
            "ayah": 41
        },
        "end": {
            "surah": 9,
            "ayah": 36
        }
    },
    {
        "start": {
            "surah": 9,
            "ayah": 37
        },
        "end": {
            "surah": 9,
            "ayah": 93
        }
    },
    {
        "start": {
            "surah": 9,
            "ayah": 94
        },
        "end": {
            "surah": 10,
            "ayah": 25
        }
    },
    {
        "start": {
            "surah": 10,
            "ayah": 26
        },
        "end": {
            "surah": 11,
            "ayah": 5
        }
    },
    {
        "start": {
            "surah": 11,
            "ayah": 6
        },
        "end": {
            "surah": 11,
            "ayah": 88
        }
    },
    {
        "start": {
            "surah": 11,
            "ayah": 89
        },
        "end": {
            "surah": 12,
            "ayah": 52
        }
    },
    {
        "start": {
            "surah": 12,
            "ayah": 53
        },
        "end": {
            "surah": 13,
            "ayah": 18
        }
    },
    {
        "start": {
            "surah": 13,
            "ayah": 19
        },
        "end": {
            "surah": 14,
            "ayah": 52
        }
    },
    {
        "start": {
            "surah": 15,
            "ayah": 1
        },
        "end": {
            "surah": 16,
            "ayah": 54
        }
    },
    {
        "start": {
            "surah": 16,
            "ayah": 55
        },
        "end": {
            "surah": 16,
            "ayah": 128
        }
    },
    {
        "start": {
            "surah": 17,
            "ayah": 1
        },
        "end": {
            "surah": 17,
            "ayah": 104
        }
    },
    {
        "start": {
            "surah": 17,
            "ayah": 105
        },
        "end": {
            "surah": 18,
            "ayah": 74
        }
    },
    {
        "start": {
            "surah": 18,
            "ayah": 75
        },
        "end": {
            "surah": 20,
            "ayah": 12
        }
    },
    {
        "start": {
            "surah": 20,
            "ayah": 13
        },
        "end": {
            "surah": 20,
            "ayah": 135
        }
    },
    {
        "start": {
            "surah": 21,
            "ayah": 1
        },
        "end": {
            "surah": 21,
            "ayah": 112
        }
    },
    {
        "start": {
            "surah": 22,
            "ayah": 1
        },
        "end": {
            "surah": 22,
            "ayah": 78
        }
    },
    {
        "start": {
            "surah": 23,
            "ayah": 1
        },
        "end": {
            "surah": 24,
            "ayah": 20
        }
    },
    {
        "start": {
            "surah": 24,
            "ayah": 21
        },
        "end": {
            "surah": 25,
            "ayah": 20
        }
    },
    {
        "start": {
            "surah": 25,
            "ayah": 21
        },
        "end": {
            "surah": 26,
            "ayah": 111
        }
    },
    {
        "start": {
            "surah": 26,
            "ayah": 112
        },
        "end": {
            "surah": 27,
            "ayah": 55
        }
    },
    {
        "start": {
            "surah": 27,
            "ayah": 56
        },
        "end": {
            "surah": 28,
            "ayah": 50
        }
    },
    {
        "start": {
            "surah": 28,
            "ayah": 51
        },
        "end": {
            "surah": 29,
            "ayah": 45
        }
    },
    {
        "start": {
            "surah": 29,
            "ayah": 46
        },
        "end": {
            "surah": 31,
            "ayah": 28
        }
    },
    {
        "start": {
            "surah": 31,
            "ayah": 29
        },
        "end": {
            "surah": 33,
            "ayah": 30
        }
    },
    {
        "start": {
            "surah": 33,
            "ayah": 31
        },
        "end": {
            "surah": 34,
            "ayah": 31
        }
    },
    {
        "start": {
            "surah": 34,
            "ayah": 32
        },
        "end": {
            "surah": 36,
            "ayah": 27
        }
    },
    {
        "start": {
            "surah": 36,
            "ayah": 28
        },
        "end": {
            "surah": 37,
            "ayah": 153
        }
    },
    {
        "start": {
            "surah": 37,
            "ayah": 154
        },
        "end": {
            "surah": 39,
            "ayah": 31
        }
    },
    {
        "start": {
            "surah": 39,
            "ayah": 32
        },
        "end": {
            "surah": 40,
            "ayah": 40
        }
    },
    {
        "start": {
            "surah": 40,
            "ayah": 41
        },
        "end": {
            "surah": 41,
            "ayah": 46
        }
    },
    {
        "start": {
            "surah": 41,
            "ayah": 47
        },
        "end": {
            "surah": 43,
            "ayah": 33
        }
    },
    {
        "start": {
            "surah": 43,
            "ayah": 34
        },
        "end": {
            "surah": 46,
            "ayah": 5
        }
    },
    {
        "start": {
            "surah": 46,
            "ayah": 6
        },
        "end": {
            "surah": 48,
            "ayah": 23
        }
    },
    {
        "start": {
            "surah": 48,
            "ayah": 24
        },
        "end": {
            "surah": 51,
            "ayah": 30
        }
    },
    {
        "start": {
            "surah": 51,
            "ayah": 31
        },
        "end": {
            "surah": 55,
            "ayah": 16
        }
    },
    {
        "start": {
            "surah": 55,
            "ayah": 17
        },
        "end": {
            "surah": 57,
            "ayah": 29
        }
    },
    {
        "start": {
            "surah": 58,
            "ayah": 1
        },
        "end": {
            "surah": 61,
            "ayah": 14
        }
    },
    {
        "start": {
            "surah": 62,
            "ayah": 1
        },
        "end": {
            "surah": 66,
            "ayah": 12
        }
    },
    {
        "start": {
            "surah": 67,
            "ayah": 1
        },
        "end": {
            "surah": 71,
            "ayah": 28
        }
    },
    {
        "start": {
            "surah": 72,
            "ayah": 1
        },
        "end": {
            "surah": 77,
            "ayah": 50
        }
    },
    {
        "start": {
            "surah": 78,
            "ayah": 1
        },
        "end": {
            "surah": 87,
            "ayah": 15
        }
    },
    {
        "start": {
            "surah": 87,
            "ayah": 16
        },
        "end": {
            "surah": 114,
            "ayah": 6
        }
    }
];

export const RUB_BOUNDARIES: (StructureBoundary | null)[] = [
    {
        "start": {
            "surah": 1,
            "ayah": 1
        },
        "end": {
            "surah": 2,
            "ayah": 29
        }
    },
    {
        "start": {
            "surah": 2,
            "ayah": 30
        },
        "end": {
            "surah": 2,
            "ayah": 48
        }
    },
    {
        "start": {
            "surah": 2,
            "ayah": 49
        },
        "end": {
            "surah": 2,
            "ayah": 61
        }
    },
    {
        "start": {
            "surah": 2,
            "ayah": 62
        },
        "end": {
            "surah": 2,
            "ayah": 76
        }
    },
    {
        "start": {
            "surah": 2,
            "ayah": 77
        },
        "end": {
            "surah": 2,
            "ayah": 93
        }
    },
    {
        "start": {
            "surah": 2,
            "ayah": 94
        },
        "end": {
            "surah": 2,
            "ayah": 105
        }
    },
    {
        "start": {
            "surah": 2,
            "ayah": 106
        },
        "end": {
            "surah": 2,
            "ayah": 126
        }
    },
    {
        "start": {
            "surah": 2,
            "ayah": 127
        },
        "end": {
            "surah": 2,
            "ayah": 141
        }
    },
    {
        "start": {
            "surah": 2,
            "ayah": 142
        },
        "end": {
            "surah": 2,
            "ayah": 163
        }
    },
    {
        "start": {
            "surah": 2,
            "ayah": 164
        },
        "end": {
            "surah": 2,
            "ayah": 176
        }
    },
    {
        "start": {
            "surah": 2,
            "ayah": 177
        },
        "end": {
            "surah": 2,
            "ayah": 190
        }
    },
    {
        "start": {
            "surah": 2,
            "ayah": 191
        },
        "end": {
            "surah": 2,
            "ayah": 202
        }
    },
    {
        "start": {
            "surah": 2,
            "ayah": 203
        },
        "end": {
            "surah": 2,
            "ayah": 219
        }
    },
    {
        "start": {
            "surah": 2,
            "ayah": 220
        },
        "end": {
            "surah": 2,
            "ayah": 233
        }
    },
    {
        "start": {
            "surah": 2,
            "ayah": 234
        },
        "end": {
            "surah": 2,
            "ayah": 245
        }
    },
    {
        "start": {
            "surah": 2,
            "ayah": 246
        },
        "end": {
            "surah": 2,
            "ayah": 252
        }
    },
    {
        "start": {
            "surah": 2,
            "ayah": 253
        },
        "end": {
            "surah": 2,
            "ayah": 264
        }
    },
    {
        "start": {
            "surah": 2,
            "ayah": 265
        },
        "end": {
            "surah": 2,
            "ayah": 274
        }
    },
    {
        "start": {
            "surah": 2,
            "ayah": 275
        },
        "end": {
            "surah": 2,
            "ayah": 282
        }
    },
    {
        "start": {
            "surah": 2,
            "ayah": 283
        },
        "end": {
            "surah": 3,
            "ayah": 15
        }
    },
    {
        "start": {
            "surah": 3,
            "ayah": 16
        },
        "end": {
            "surah": 3,
            "ayah": 37
        }
    },
    {
        "start": {
            "surah": 3,
            "ayah": 38
        },
        "end": {
            "surah": 3,
            "ayah": 52
        }
    },
    {
        "start": {
            "surah": 3,
            "ayah": 53
        },
        "end": {
            "surah": 3,
            "ayah": 77
        }
    },
    {
        "start": {
            "surah": 3,
            "ayah": 78
        },
        "end": {
            "surah": 3,
            "ayah": 100
        }
    },
    {
        "start": {
            "surah": 3,
            "ayah": 101
        },
        "end": {
            "surah": 3,
            "ayah": 115
        }
    },
    {
        "start": {
            "surah": 3,
            "ayah": 116
        },
        "end": {
            "surah": 3,
            "ayah": 132
        }
    },
    {
        "start": {
            "surah": 3,
            "ayah": 133
        },
        "end": {
            "surah": 3,
            "ayah": 153
        }
    },
    {
        "start": {
            "surah": 3,
            "ayah": 154
        },
        "end": {
            "surah": 3,
            "ayah": 173
        }
    },
    {
        "start": {
            "surah": 3,
            "ayah": 174
        },
        "end": {
            "surah": 3,
            "ayah": 186
        }
    },
    {
        "start": {
            "surah": 3,
            "ayah": 187
        },
        "end": {
            "surah": 3,
            "ayah": 200
        }
    },
    {
        "start": {
            "surah": 4,
            "ayah": 1
        },
        "end": {
            "surah": 4,
            "ayah": 11
        }
    },
    {
        "start": {
            "surah": 4,
            "ayah": 12
        },
        "end": {
            "surah": 4,
            "ayah": 23
        }
    },
    {
        "start": {
            "surah": 4,
            "ayah": 24
        },
        "end": {
            "surah": 4,
            "ayah": 37
        }
    },
    {
        "start": {
            "surah": 4,
            "ayah": 38
        },
        "end": {
            "surah": 4,
            "ayah": 59
        }
    },
    {
        "start": {
            "surah": 4,
            "ayah": 60
        },
        "end": {
            "surah": 4,
            "ayah": 74
        }
    },
    {
        "start": {
            "surah": 4,
            "ayah": 75
        },
        "end": {
            "surah": 4,
            "ayah": 91
        }
    },
    {
        "start": {
            "surah": 4,
            "ayah": 92
        },
        "end": {
            "surah": 4,
            "ayah": 101
        }
    },
    {
        "start": {
            "surah": 4,
            "ayah": 102
        },
        "end": {
            "surah": 4,
            "ayah": 113
        }
    },
    {
        "start": {
            "surah": 4,
            "ayah": 114
        },
        "end": {
            "surah": 4,
            "ayah": 134
        }
    },
    {
        "start": {
            "surah": 4,
            "ayah": 135
        },
        "end": {
            "surah": 4,
            "ayah": 147
        }
    },
    {
        "start": {
            "surah": 4,
            "ayah": 148
        },
        "end": {
            "surah": 4,
            "ayah": 162
        }
    },
    {
        "start": {
            "surah": 4,
            "ayah": 163
        },
        "end": {
            "surah": 5,
            "ayah": 2
        }
    },
    {
        "start": {
            "surah": 5,
            "ayah": 3
        },
        "end": {
            "surah": 5,
            "ayah": 13
        }
    },
    {
        "start": {
            "surah": 5,
            "ayah": 14
        },
        "end": {
            "surah": 5,
            "ayah": 31
        }
    },
    {
        "start": {
            "surah": 5,
            "ayah": 32
        },
        "end": {
            "surah": 5,
            "ayah": 41
        }
    },
    {
        "start": {
            "surah": 5,
            "ayah": 42
        },
        "end": {
            "surah": 5,
            "ayah": 50
        }
    },
    {
        "start": {
            "surah": 5,
            "ayah": 51
        },
        "end": {
            "surah": 5,
            "ayah": 70
        }
    },
    {
        "start": {
            "surah": 5,
            "ayah": 71
        },
        "end": {
            "surah": 5,
            "ayah": 82
        }
    },
    {
        "start": {
            "surah": 5,
            "ayah": 83
        },
        "end": {
            "surah": 5,
            "ayah": 103
        }
    },
    {
        "start": {
            "surah": 5,
            "ayah": 104
        },
        "end": {
            "surah": 5,
            "ayah": 108
        }
    },
    {
        "start": {
            "surah": 5,
            "ayah": 109
        },
        "end": {
            "surah": 6,
            "ayah": 18
        }
    },
    {
        "start": {
            "surah": 6,
            "ayah": 19
        },
        "end": {
            "surah": 6,
            "ayah": 35
        }
    },
    {
        "start": {
            "surah": 6,
            "ayah": 36
        },
        "end": {
            "surah": 6,
            "ayah": 59
        }
    },
    {
        "start": {
            "surah": 6,
            "ayah": 60
        },
        "end": {
            "surah": 6,
            "ayah": 73
        }
    },
    {
        "start": {
            "surah": 6,
            "ayah": 74
        },
        "end": {
            "surah": 6,
            "ayah": 94
        }
    },
    {
        "start": {
            "surah": 6,
            "ayah": 95
        },
        "end": {
            "surah": 6,
            "ayah": 110
        }
    },
    {
        "start": {
            "surah": 6,
            "ayah": 111
        },
        "end": {
            "surah": 6,
            "ayah": 131
        }
    },
    {
        "start": {
            "surah": 6,
            "ayah": 132
        },
        "end": {
            "surah": 6,
            "ayah": 142
        }
    },
    {
        "start": {
            "surah": 6,
            "ayah": 143
        },
        "end": {
            "surah": 6,
            "ayah": 151
        }
    },
    {
        "start": {
            "surah": 6,
            "ayah": 152
        },
        "end": {
            "surah": 6,
            "ayah": 165
        }
    },
    {
        "start": {
            "surah": 7,
            "ayah": 1
        },
        "end": {
            "surah": 7,
            "ayah": 30
        }
    },
    {
        "start": {
            "surah": 7,
            "ayah": 31
        },
        "end": {
            "surah": 7,
            "ayah": 51
        }
    },
    {
        "start": {
            "surah": 7,
            "ayah": 52
        },
        "end": {
            "surah": 7,
            "ayah": 67
        }
    },
    {
        "start": {
            "surah": 7,
            "ayah": 68
        },
        "end": {
            "surah": 7,
            "ayah": 87
        }
    },
    {
        "start": {
            "surah": 7,
            "ayah": 88
        },
        "end": {
            "surah": 7,
            "ayah": 120
        }
    },
    {
        "start": {
            "surah": 7,
            "ayah": 121
        },
        "end": {
            "surah": 7,
            "ayah": 143
        }
    },
    {
        "start": {
            "surah": 7,
            "ayah": 144
        },
        "end": {
            "surah": 7,
            "ayah": 155
        }
    },
    {
        "start": {
            "surah": 7,
            "ayah": 156
        },
        "end": {
            "surah": 7,
            "ayah": 170
        }
    },
    {
        "start": {
            "surah": 7,
            "ayah": 171
        },
        "end": {
            "surah": 7,
            "ayah": 195
        }
    },
    {
        "start": {
            "surah": 7,
            "ayah": 196
        },
        "end": {
            "surah": 7,
            "ayah": 206
        }
    },
    {
        "start": {
            "surah": 8,
            "ayah": 1
        },
        "end": {
            "surah": 8,
            "ayah": 25
        }
    },
    {
        "start": {
            "surah": 8,
            "ayah": 26
        },
        "end": {
            "surah": 8,
            "ayah": 40
        }
    },
    {
        "start": {
            "surah": 8,
            "ayah": 41
        },
        "end": {
            "surah": 8,
            "ayah": 61
        }
    },
    {
        "start": {
            "surah": 8,
            "ayah": 62
        },
        "end": {
            "surah": 8,
            "ayah": 75
        }
    },
    {
        "start": {
            "surah": 9,
            "ayah": 1
        },
        "end": {
            "surah": 9,
            "ayah": 20
        }
    },
    {
        "start": {
            "surah": 9,
            "ayah": 21
        },
        "end": {
            "surah": 9,
            "ayah": 36
        }
    },
    {
        "start": {
            "surah": 9,
            "ayah": 37
        },
        "end": {
            "surah": 9,
            "ayah": 47
        }
    },
    {
        "start": {
            "surah": 9,
            "ayah": 48
        },
        "end": {
            "surah": 9,
            "ayah": 61
        }
    },
    {
        "start": {
            "surah": 9,
            "ayah": 62
        },
        "end": {
            "surah": 9,
            "ayah": 79
        }
    },
    {
        "start": {
            "surah": 9,
            "ayah": 80
        },
        "end": {
            "surah": 9,
            "ayah": 93
        }
    },
    {
        "start": {
            "surah": 9,
            "ayah": 94
        },
        "end": {
            "surah": 9,
            "ayah": 111
        }
    },
    {
        "start": {
            "surah": 9,
            "ayah": 112
        },
        "end": {
            "surah": 9,
            "ayah": 122
        }
    },
    {
        "start": {
            "surah": 9,
            "ayah": 123
        },
        "end": {
            "surah": 10,
            "ayah": 14
        }
    },
    {
        "start": {
            "surah": 10,
            "ayah": 15
        },
        "end": {
            "surah": 10,
            "ayah": 25
        }
    },
    {
        "start": {
            "surah": 10,
            "ayah": 26
        },
        "end": {
            "surah": 10,
            "ayah": 53
        }
    },
    {
        "start": {
            "surah": 10,
            "ayah": 54
        },
        "end": {
            "surah": 10,
            "ayah": 70
        }
    },
    {
        "start": {
            "surah": 10,
            "ayah": 71
        },
        "end": {
            "surah": 10,
            "ayah": 97
        }
    },
    {
        "start": {
            "surah": 10,
            "ayah": 98
        },
        "end": {
            "surah": 11,
            "ayah": 5
        }
    },
    {
        "start": {
            "surah": 11,
            "ayah": 6
        },
        "end": {
            "surah": 11,
            "ayah": 28
        }
    },
    {
        "start": {
            "surah": 11,
            "ayah": 29
        },
        "end": {
            "surah": 11,
            "ayah": 45
        }
    },
    {
        "start": {
            "surah": 11,
            "ayah": 46
        },
        "end": {
            "surah": 11,
            "ayah": 62
        }
    },
    {
        "start": {
            "surah": 11,
            "ayah": 63
        },
        "end": {
            "surah": 11,
            "ayah": 88
        }
    },
    {
        "start": {
            "surah": 11,
            "ayah": 89
        },
        "end": {
            "surah": 11,
            "ayah": 108
        }
    },
    {
        "start": {
            "surah": 11,
            "ayah": 109
        },
        "end": {
            "surah": 12,
            "ayah": 14
        }
    },
    {
        "start": {
            "surah": 12,
            "ayah": 15
        },
        "end": {
            "surah": 12,
            "ayah": 30
        }
    },
    {
        "start": {
            "surah": 12,
            "ayah": 31
        },
        "end": {
            "surah": 12,
            "ayah": 52
        }
    },
    {
        "start": {
            "surah": 12,
            "ayah": 53
        },
        "end": {
            "surah": 12,
            "ayah": 78
        }
    },
    {
        "start": {
            "surah": 12,
            "ayah": 79
        },
        "end": {
            "surah": 12,
            "ayah": 103
        }
    },
    {
        "start": {
            "surah": 12,
            "ayah": 104
        },
        "end": {
            "surah": 13,
            "ayah": 5
        }
    },
    {
        "start": {
            "surah": 13,
            "ayah": 6
        },
        "end": {
            "surah": 13,
            "ayah": 18
        }
    },
    {
        "start": {
            "surah": 13,
            "ayah": 19
        },
        "end": {
            "surah": 13,
            "ayah": 34
        }
    },
    {
        "start": {
            "surah": 13,
            "ayah": 35
        },
        "end": {
            "surah": 14,
            "ayah": 10
        }
    },
    {
        "start": {
            "surah": 14,
            "ayah": 11
        },
        "end": {
            "surah": 14,
            "ayah": 33
        }
    },
    {
        "start": {
            "surah": 14,
            "ayah": 34
        },
        "end": {
            "surah": 14,
            "ayah": 52
        }
    },
    {
        "start": {
            "surah": 15,
            "ayah": 1
        },
        "end": {
            "surah": 15,
            "ayah": 51
        }
    },
    {
        "start": {
            "surah": 15,
            "ayah": 52
        },
        "end": {
            "surah": 16,
            "ayah": 6
        }
    },
    {
        "start": {
            "surah": 16,
            "ayah": 7
        },
        "end": {
            "surah": 16,
            "ayah": 34
        }
    },
    {
        "start": {
            "surah": 16,
            "ayah": 35
        },
        "end": {
            "surah": 16,
            "ayah": 54
        }
    },
    {
        "start": {
            "surah": 16,
            "ayah": 55
        },
        "end": {
            "surah": 16,
            "ayah": 79
        }
    },
    {
        "start": {
            "surah": 16,
            "ayah": 80
        },
        "end": {
            "surah": 16,
            "ayah": 93
        }
    },
    {
        "start": {
            "surah": 16,
            "ayah": 94
        },
        "end": {
            "surah": 16,
            "ayah": 110
        }
    },
    {
        "start": {
            "surah": 16,
            "ayah": 111
        },
        "end": {
            "surah": 16,
            "ayah": 128
        }
    },
    {
        "start": {
            "surah": 17,
            "ayah": 1
        },
        "end": {
            "surah": 17,
            "ayah": 27
        }
    },
    {
        "start": {
            "surah": 17,
            "ayah": 28
        },
        "end": {
            "surah": 17,
            "ayah": 49
        }
    },
    {
        "start": {
            "surah": 17,
            "ayah": 50
        },
        "end": {
            "surah": 17,
            "ayah": 75
        }
    },
    {
        "start": {
            "surah": 17,
            "ayah": 76
        },
        "end": {
            "surah": 17,
            "ayah": 104
        }
    },
    {
        "start": {
            "surah": 17,
            "ayah": 105
        },
        "end": {
            "surah": 18,
            "ayah": 20
        }
    },
    {
        "start": {
            "surah": 18,
            "ayah": 21
        },
        "end": {
            "surah": 18,
            "ayah": 34
        }
    },
    {
        "start": {
            "surah": 18,
            "ayah": 35
        },
        "end": {
            "surah": 18,
            "ayah": 53
        }
    },
    {
        "start": {
            "surah": 18,
            "ayah": 54
        },
        "end": {
            "surah": 18,
            "ayah": 74
        }
    },
    {
        "start": {
            "surah": 18,
            "ayah": 75
        },
        "end": {
            "surah": 18,
            "ayah": 110
        }
    },
    {
        "start": {
            "surah": 19,
            "ayah": 1
        },
        "end": {
            "surah": 19,
            "ayah": 25
        }
    },
    {
        "start": {
            "surah": 19,
            "ayah": 26
        },
        "end": {
            "surah": 19,
            "ayah": 64
        }
    },
    {
        "start": {
            "surah": 19,
            "ayah": 65
        },
        "end": {
            "surah": 20,
            "ayah": 12
        }
    },
    {
        "start": {
            "surah": 20,
            "ayah": 13
        },
        "end": {
            "surah": 20,
            "ayah": 64
        }
    },
    {
        "start": {
            "surah": 20,
            "ayah": 65
        },
        "end": {
            "surah": 20,
            "ayah": 87
        }
    },
    {
        "start": {
            "surah": 20,
            "ayah": 88
        },
        "end": {
            "surah": 20,
            "ayah": 113
        }
    },
    {
        "start": {
            "surah": 20,
            "ayah": 114
        },
        "end": {
            "surah": 20,
            "ayah": 135
        }
    },
    {
        "start": {
            "surah": 21,
            "ayah": 1
        },
        "end": {
            "surah": 21,
            "ayah": 35
        }
    },
    {
        "start": {
            "surah": 21,
            "ayah": 36
        },
        "end": {
            "surah": 21,
            "ayah": 57
        }
    },
    {
        "start": {
            "surah": 21,
            "ayah": 58
        },
        "end": {
            "surah": 21,
            "ayah": 90
        }
    },
    {
        "start": {
            "surah": 21,
            "ayah": 91
        },
        "end": {
            "surah": 21,
            "ayah": 112
        }
    },
    {
        "start": {
            "surah": 22,
            "ayah": 1
        },
        "end": {
            "surah": 22,
            "ayah": 23
        }
    },
    {
        "start": {
            "surah": 22,
            "ayah": 24
        },
        "end": {
            "surah": 22,
            "ayah": 38
        }
    },
    {
        "start": {
            "surah": 22,
            "ayah": 39
        },
        "end": {
            "surah": 22,
            "ayah": 64
        }
    },
    {
        "start": {
            "surah": 22,
            "ayah": 65
        },
        "end": {
            "surah": 22,
            "ayah": 78
        }
    },
    {
        "start": {
            "surah": 23,
            "ayah": 1
        },
        "end": {
            "surah": 23,
            "ayah": 42
        }
    },
    {
        "start": {
            "surah": 23,
            "ayah": 43
        },
        "end": {
            "surah": 23,
            "ayah": 74
        }
    },
    {
        "start": {
            "surah": 23,
            "ayah": 75
        },
        "end": {
            "surah": 23,
            "ayah": 118
        }
    },
    {
        "start": {
            "surah": 24,
            "ayah": 1
        },
        "end": {
            "surah": 24,
            "ayah": 20
        }
    },
    {
        "start": {
            "surah": 24,
            "ayah": 21
        },
        "end": {
            "surah": 24,
            "ayah": 36
        }
    },
    {
        "start": {
            "surah": 24,
            "ayah": 37
        },
        "end": {
            "surah": 24,
            "ayah": 53
        }
    },
    {
        "start": {
            "surah": 24,
            "ayah": 54
        },
        "end": {
            "surah": 25,
            "ayah": 2
        }
    },
    {
        "start": {
            "surah": 25,
            "ayah": 3
        },
        "end": {
            "surah": 25,
            "ayah": 20
        }
    },
    {
        "start": {
            "surah": 25,
            "ayah": 21
        },
        "end": {
            "surah": 25,
            "ayah": 55
        }
    },
    {
        "start": {
            "surah": 25,
            "ayah": 56
        },
        "end": {
            "surah": 25,
            "ayah": 77
        }
    },
    {
        "start": {
            "surah": 26,
            "ayah": 1
        },
        "end": {
            "surah": 26,
            "ayah": 60
        }
    },
    {
        "start": {
            "surah": 26,
            "ayah": 61
        },
        "end": {
            "surah": 26,
            "ayah": 111
        }
    },
    {
        "start": {
            "surah": 26,
            "ayah": 112
        },
        "end": {
            "surah": 26,
            "ayah": 183
        }
    },
    {
        "start": {
            "surah": 26,
            "ayah": 184
        },
        "end": {
            "surah": 26,
            "ayah": 227
        }
    },
    {
        "start": {
            "surah": 27,
            "ayah": 1
        },
        "end": {
            "surah": 27,
            "ayah": 35
        }
    },
    {
        "start": {
            "surah": 27,
            "ayah": 36
        },
        "end": {
            "surah": 27,
            "ayah": 55
        }
    },
    {
        "start": {
            "surah": 27,
            "ayah": 56
        },
        "end": {
            "surah": 27,
            "ayah": 88
        }
    },
    {
        "start": {
            "surah": 27,
            "ayah": 89
        },
        "end": {
            "surah": 28,
            "ayah": 13
        }
    },
    {
        "start": {
            "surah": 28,
            "ayah": 14
        },
        "end": {
            "surah": 28,
            "ayah": 28
        }
    },
    {
        "start": {
            "surah": 28,
            "ayah": 29
        },
        "end": {
            "surah": 28,
            "ayah": 50
        }
    },
    {
        "start": {
            "surah": 28,
            "ayah": 51
        },
        "end": {
            "surah": 28,
            "ayah": 77
        }
    },
    {
        "start": {
            "surah": 28,
            "ayah": 78
        },
        "end": {
            "surah": 29,
            "ayah": 6
        }
    },
    {
        "start": {
            "surah": 29,
            "ayah": 7
        },
        "end": {
            "surah": 29,
            "ayah": 30
        }
    },
    {
        "start": {
            "surah": 29,
            "ayah": 31
        },
        "end": {
            "surah": 29,
            "ayah": 45
        }
    },
    {
        "start": {
            "surah": 29,
            "ayah": 46
        },
        "end": {
            "surah": 30,
            "ayah": 5
        }
    },
    {
        "start": {
            "surah": 30,
            "ayah": 6
        },
        "end": {
            "surah": 30,
            "ayah": 32
        }
    },
    {
        "start": {
            "surah": 30,
            "ayah": 33
        },
        "end": {
            "surah": 30,
            "ayah": 60
        }
    },
    {
        "start": {
            "surah": 31,
            "ayah": 1
        },
        "end": {
            "surah": 31,
            "ayah": 28
        }
    },
    {
        "start": {
            "surah": 31,
            "ayah": 29
        },
        "end": {
            "surah": 32,
            "ayah": 11
        }
    },
    {
        "start": {
            "surah": 32,
            "ayah": 12
        },
        "end": {
            "surah": 32,
            "ayah": 30
        }
    },
    {
        "start": {
            "surah": 33,
            "ayah": 1
        },
        "end": {
            "surah": 33,
            "ayah": 22
        }
    },
    {
        "start": {
            "surah": 33,
            "ayah": 23
        },
        "end": {
            "surah": 33,
            "ayah": 30
        }
    },
    {
        "start": {
            "surah": 33,
            "ayah": 31
        },
        "end": {
            "surah": 33,
            "ayah": 50
        }
    },
    {
        "start": {
            "surah": 33,
            "ayah": 51
        },
        "end": {
            "surah": 33,
            "ayah": 62
        }
    },
    {
        "start": {
            "surah": 33,
            "ayah": 63
        },
        "end": {
            "surah": 34,
            "ayah": 14
        }
    },
    {
        "start": {
            "surah": 34,
            "ayah": 15
        },
        "end": {
            "surah": 34,
            "ayah": 31
        }
    },
    {
        "start": {
            "surah": 34,
            "ayah": 32
        },
        "end": {
            "surah": 34,
            "ayah": 48
        }
    },
    {
        "start": {
            "surah": 34,
            "ayah": 49
        },
        "end": {
            "surah": 35,
            "ayah": 18
        }
    },
    {
        "start": {
            "surah": 35,
            "ayah": 19
        },
        "end": {
            "surah": 35,
            "ayah": 44
        }
    },
    {
        "start": {
            "surah": 35,
            "ayah": 45
        },
        "end": {
            "surah": 36,
            "ayah": 27
        }
    },
    {
        "start": {
            "surah": 36,
            "ayah": 28
        },
        "end": {
            "surah": 36,
            "ayah": 70
        }
    },
    {
        "start": {
            "surah": 36,
            "ayah": 71
        },
        "end": {
            "surah": 37,
            "ayah": 24
        }
    },
    {
        "start": {
            "surah": 37,
            "ayah": 25
        },
        "end": {
            "surah": 37,
            "ayah": 102
        }
    },
    {
        "start": {
            "surah": 37,
            "ayah": 103
        },
        "end": {
            "surah": 37,
            "ayah": 153
        }
    },
    {
        "start": {
            "surah": 37,
            "ayah": 154
        },
        "end": {
            "surah": 38,
            "ayah": 26
        }
    },
    {
        "start": {
            "surah": 38,
            "ayah": 27
        },
        "end": {
            "surah": 38,
            "ayah": 61
        }
    },
    {
        "start": {
            "surah": 38,
            "ayah": 62
        },
        "end": {
            "surah": 39,
            "ayah": 10
        }
    },
    {
        "start": {
            "surah": 39,
            "ayah": 11
        },
        "end": {
            "surah": 39,
            "ayah": 31
        }
    },
    {
        "start": {
            "surah": 39,
            "ayah": 32
        },
        "end": {
            "surah": 39,
            "ayah": 56
        }
    },
    {
        "start": {
            "surah": 39,
            "ayah": 57
        },
        "end": {
            "surah": 40,
            "ayah": 7
        }
    },
    {
        "start": {
            "surah": 40,
            "ayah": 8
        },
        "end": {
            "surah": 40,
            "ayah": 25
        }
    },
    {
        "start": {
            "surah": 40,
            "ayah": 26
        },
        "end": {
            "surah": 40,
            "ayah": 40
        }
    },
    {
        "start": {
            "surah": 40,
            "ayah": 41
        },
        "end": {
            "surah": 40,
            "ayah": 66
        }
    },
    {
        "start": {
            "surah": 40,
            "ayah": 67
        },
        "end": {
            "surah": 41,
            "ayah": 11
        }
    },
    {
        "start": {
            "surah": 41,
            "ayah": 12
        },
        "end": {
            "surah": 41,
            "ayah": 29
        }
    },
    {
        "start": {
            "surah": 41,
            "ayah": 30
        },
        "end": {
            "surah": 41,
            "ayah": 46
        }
    },
    {
        "start": {
            "surah": 41,
            "ayah": 47
        },
        "end": {
            "surah": 42,
            "ayah": 15
        }
    },
    {
        "start": {
            "surah": 42,
            "ayah": 16
        },
        "end": {
            "surah": 42,
            "ayah": 31
        }
    },
    {
        "start": {
            "surah": 42,
            "ayah": 32
        },
        "end": {
            "surah": 42,
            "ayah": 51
        }
    },
    {
        "start": {
            "surah": 42,
            "ayah": 52
        },
        "end": {
            "surah": 43,
            "ayah": 33
        }
    },
    {
        "start": {
            "surah": 43,
            "ayah": 34
        },
        "end": {
            "surah": 43,
            "ayah": 60
        }
    },
    {
        "start": {
            "surah": 43,
            "ayah": 61
        },
        "end": {
            "surah": 44,
            "ayah": 18
        }
    },
    {
        "start": {
            "surah": 44,
            "ayah": 19
        },
        "end": {
            "surah": 45,
            "ayah": 13
        }
    },
    {
        "start": {
            "surah": 45,
            "ayah": 14
        },
        "end": {
            "surah": 46,
            "ayah": 5
        }
    },
    {
        "start": {
            "surah": 46,
            "ayah": 6
        },
        "end": {
            "surah": 46,
            "ayah": 20
        }
    },
    {
        "start": {
            "surah": 46,
            "ayah": 21
        },
        "end": {
            "surah": 47,
            "ayah": 11
        }
    },
    {
        "start": {
            "surah": 47,
            "ayah": 12
        },
        "end": {
            "surah": 47,
            "ayah": 38
        }
    },
    {
        "start": {
            "surah": 48,
            "ayah": 1
        },
        "end": {
            "surah": 48,
            "ayah": 23
        }
    },
    {
        "start": {
            "surah": 48,
            "ayah": 24
        },
        "end": {
            "surah": 49,
            "ayah": 4
        }
    },
    {
        "start": {
            "surah": 49,
            "ayah": 5
        },
        "end": {
            "surah": 49,
            "ayah": 18
        }
    },
    {
        "start": {
            "surah": 50,
            "ayah": 1
        },
        "end": {
            "surah": 50,
            "ayah": 35
        }
    },
    {
        "start": {
            "surah": 50,
            "ayah": 36
        },
        "end": {
            "surah": 51,
            "ayah": 30
        }
    },
    {
        "start": {
            "surah": 51,
            "ayah": 31
        },
        "end": {
            "surah": 52,
            "ayah": 31
        }
    },
    {
        "start": {
            "surah": 52,
            "ayah": 32
        },
        "end": {
            "surah": 53,
            "ayah": 26
        }
    },
    {
        "start": {
            "surah": 53,
            "ayah": 27
        },
        "end": {
            "surah": 54,
            "ayah": 27
        }
    },
    {
        "start": {
            "surah": 54,
            "ayah": 28
        },
        "end": {
            "surah": 55,
            "ayah": 16
        }
    },
    {
        "start": {
            "surah": 55,
            "ayah": 17
        },
        "end": {
            "surah": 56,
            "ayah": 16
        }
    },
    {
        "start": {
            "surah": 56,
            "ayah": 17
        },
        "end": {
            "surah": 56,
            "ayah": 76
        }
    },
    {
        "start": {
            "surah": 56,
            "ayah": 77
        },
        "end": {
            "surah": 57,
            "ayah": 18
        }
    },
    {
        "start": {
            "surah": 57,
            "ayah": 19
        },
        "end": {
            "surah": 57,
            "ayah": 29
        }
    },
    {
        "start": {
            "surah": 58,
            "ayah": 1
        },
        "end": {
            "surah": 58,
            "ayah": 21
        }
    },
    {
        "start": {
            "surah": 58,
            "ayah": 22
        },
        "end": {
            "surah": 59,
            "ayah": 16
        }
    },
    {
        "start": {
            "surah": 59,
            "ayah": 17
        },
        "end": {
            "surah": 60,
            "ayah": 11
        }
    },
    {
        "start": {
            "surah": 60,
            "ayah": 12
        },
        "end": {
            "surah": 61,
            "ayah": 14
        }
    },
    {
        "start": {
            "surah": 62,
            "ayah": 1
        },
        "end": {
            "surah": 63,
            "ayah": 4
        }
    },
    {
        "start": {
            "surah": 63,
            "ayah": 5
        },
        "end": {
            "surah": 64,
            "ayah": 18
        }
    },
    {
        "start": {
            "surah": 65,
            "ayah": 1
        },
        "end": {
            "surah": 65,
            "ayah": 12
        }
    },
    {
        "start": {
            "surah": 66,
            "ayah": 1
        },
        "end": {
            "surah": 66,
            "ayah": 12
        }
    },
    {
        "start": {
            "surah": 67,
            "ayah": 1
        },
        "end": {
            "surah": 68,
            "ayah": 15
        }
    },
    {
        "start": {
            "surah": 68,
            "ayah": 16
        },
        "end": {
            "surah": 69,
            "ayah": 8
        }
    },
    {
        "start": {
            "surah": 69,
            "ayah": 9
        },
        "end": {
            "surah": 70,
            "ayah": 39
        }
    },
    {
        "start": {
            "surah": 70,
            "ayah": 40
        },
        "end": {
            "surah": 71,
            "ayah": 28
        }
    },
    {
        "start": {
            "surah": 72,
            "ayah": 1
        },
        "end": {
            "surah": 73,
            "ayah": 19
        }
    },
    {
        "start": {
            "surah": 73,
            "ayah": 20
        },
        "end": {
            "surah": 75,
            "ayah": 19
        }
    },
    {
        "start": {
            "surah": 75,
            "ayah": 20
        },
        "end": {
            "surah": 76,
            "ayah": 25
        }
    },
    {
        "start": {
            "surah": 76,
            "ayah": 26
        },
        "end": {
            "surah": 77,
            "ayah": 50
        }
    },
    {
        "start": {
            "surah": 78,
            "ayah": 1
        },
        "end": {
            "surah": 79,
            "ayah": 46
        }
    },
    {
        "start": {
            "surah": 80,
            "ayah": 1
        },
        "end": {
            "surah": 81,
            "ayah": 29
        }
    },
    {
        "start": {
            "surah": 82,
            "ayah": 1
        },
        "end": {
            "surah": 84,
            "ayah": 25
        }
    },
    {
        "start": {
            "surah": 85,
            "ayah": 1
        },
        "end": {
            "surah": 87,
            "ayah": 15
        }
    },
    {
        "start": {
            "surah": 87,
            "ayah": 16
        },
        "end": {
            "surah": 90,
            "ayah": 20
        }
    },
    {
        "start": {
            "surah": 91,
            "ayah": 1
        },
        "end": {
            "surah": 94,
            "ayah": 8
        }
    },
    {
        "start": {
            "surah": 95,
            "ayah": 1
        },
        "end": {
            "surah": 102,
            "ayah": 8
        }
    },
    {
        "start": {
            "surah": 103,
            "ayah": 1
        },
        "end": {
            "surah": 114,
            "ayah": 6
        }
    }
];
