import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Replicate __dirname in ESM
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Paths
const MUSHAF_PATH = path.join(__dirname, '../public/qpc_v1_mushaf.json');
const PAGE_DIVISIONS_PATH = path.join(__dirname, '../constants/pageDivisions.ts');
const OUTPUT_PATH = path.join(__dirname, '../constants/structureBoundaries.ts');

// Read Mushaf
const mushaf = JSON.parse(fs.readFileSync(MUSHAF_PATH, 'utf8'));

// Read Page Divisions
// Since pageDivisions.ts is a TS file, we'll manually parse the object to avoid compilation dependencies
const pageDivisionsContent = fs.readFileSync(PAGE_DIVISIONS_PATH, 'utf8');
const match = pageDivisionsContent.match(/export const PAGE_DIVISIONS: Record<number, { juz: number, hizbQuarter: number }> = ({[\s\S]*?});/) ||
    pageDivisionsContent.match(/export const PAGE_DIVISIONS: { \[key: number\]: { juz: number, hizbQuarter: number } } = ({[\s\S]*?});/);

if (!match) {
    console.error('Could not parse PAGE_DIVISIONS from constants/pageDivisions.ts');
    process.exit(1);
}

// Evaluate the object (safely)
const PAGE_DIVISIONS = eval('(' + match[1] + ')');

// Extract Page -> Start Verse Mapping
const pageToStartVerse = {};
const pageToEndVerse = {};

mushaf.pages.forEach(page => {
    let startVerse = null;
    let endVerse = null;

    // Find first ayah on page
    for (const line of page.lines) {
        if (line.lineType === 'ayah' && line.words.length > 0) {
            const firstWord = line.words[0];
            if (!startVerse) {
                startVerse = { surah: firstWord.surah, ayah: firstWord.ayah };
            }
            const lastWord = line.words[line.words.length - 1];
            endVerse = { surah: lastWord.surah, ayah: lastWord.ayah };
        }
    }

    if (startVerse) {
        pageToStartVerse[page.pageNumber] = startVerse;
    }
    // We also need the end verse of the page to define the END of a structure
    if (endVerse) {
        pageToEndVerse[page.pageNumber] = endVerse;
    }
});

// Generate Boundaries
const juzBoundaries = []; // 1-30
const hizbBoundaries = []; // 1-60
const rubBoundaries = []; // 1-240

// Helper to get boundary
function getBoundary(startPage, endPage) {
    const start = pageToStartVerse[startPage];
    const end = pageToEndVerse[endPage];
    if (!start || !end) return null;
    return { start, end };
}

// Iterate through pages to find start/end of each structure
// We assume structure numbers are contiguous and start from 1

// We need to group pages by Juz, Hizb (calculated), and Rub
const juzPages = {};
const rubPages = {};

Object.entries(PAGE_DIVISIONS).forEach(([pageNumStr, div]) => {
    const pageNum = parseInt(pageNumStr);

    // Juz
    if (!juzPages[div.juz]) juzPages[div.juz] = [];
    juzPages[div.juz].push(pageNum);

    // Rub (hizbQuarter)
    if (!rubPages[div.hizbQuarter]) rubPages[div.hizbQuarter] = [];
    rubPages[div.hizbQuarter].push(pageNum);
});

// Generate Juz Boundaries
for (let i = 1; i <= 30; i++) {
    const pages = juzPages[i];
    if (pages) {
        pages.sort((a, b) => a - b);
        const startPage = pages[0];
        const endPage = pages[pages.length - 1];
        juzBoundaries.push(getBoundary(startPage, endPage));
    } else {
        juzBoundaries.push(null);
    }
}

// Generate Rub Boundaries
const sectionKeys = Object.keys(rubPages).map(Number).sort((a, b) => a - b);
// IMPORTANT: rubBoundaries array should correspond to index 0 = Rub 1, index 1 = Rub 2...
// We must ensure we push in correct order or fill gaps.
// The keys are 1..240.
// Let's create an array of size 240 and fill it.
for (let i = 1; i <= 240; i++) {
    const pages = rubPages[i];
    if (pages) {
        pages.sort((a, b) => a - b);
        const startPage = pages[0];
        const endPage = pages[pages.length - 1];
        rubBoundaries.push(getBoundary(startPage, endPage));
    } else {
        rubBoundaries.push(null);
    }
}

// Generate Hizb Boundaries
// Hizb 1 = Rub 1-4 (indices 0-3)
for (let i = 0; i < 60; i++) {
    const startRubIndex = i * 4;
    const endRubIndex = startRubIndex + 3;

    const startRub = rubBoundaries[startRubIndex];
    const endRub = rubBoundaries[endRubIndex];

    if (startRub && endRub) {
        hizbBoundaries.push({
            start: startRub.start,
            end: endRub.end
        });
    } else {
        hizbBoundaries.push(null);
    }
}

// Generate Output Content
const outputContent = `// This file is auto-generated by scripts/generate_structure_boundaries.js
// Do not edit manually.

export interface VerseRef {
    surah: number;
    ayah: number;
}

export interface StructureBoundary {
    start: VerseRef;
    end: VerseRef;
}

export const JUZ_BOUNDARIES: (StructureBoundary | null)[] = ${JSON.stringify(juzBoundaries, null, 4)};

export const HIZB_BOUNDARIES: (StructureBoundary | null)[] = ${JSON.stringify(hizbBoundaries, null, 4)};

export const RUB_BOUNDARIES: (StructureBoundary | null)[] = ${JSON.stringify(rubBoundaries, null, 4)};
`;

fs.writeFileSync(OUTPUT_PATH, outputContent);
console.log('Structure boundaries generated successfully!');
