/*
 * يطبّق ترجمة مصطلحات «التذكيرات» على كل ملفات اللغة.
 * - يضيف المفتاح الجديد reminders بعد notifications مباشرة.
 * - يحدّث 18 مفتاحاً بقيمها الجديدة لكل لغة.
 * - يترك المفاتيح التي لا تتغير (daily, weekly, notificationJuzHizb) كما هي.
 * - يحافظ على ترتيب المفاتيح الأصلية والتنسيق (مسافتان بادئتان).
 * - يتحقق من سلامة كل ملف JSON بعد الكتابة.
 * تشغيل: node scripts/translate_reminders.cjs
 */
'use strict';
const fs = require('fs');
const path = require('path');

const dir = path.join(__dirname, '..', 'src', 'assets', 'i18n');

// المفاتيح الـ18 التي تتغير قيمتها + reminders (الجديد)
// ترتيب إدراج reminders يُدار منفصلاً (بعد notifications)
const keys = [
  'notificationManagerTitle',
  'addNewNotification',
  'notificationType',
  'notificationTimes',
  'notificationSound',
  'uploadCustomSound',
  'enableAlarmMode',
  'alarmModeDescription',
  'deliveryMethod',
  'browserNotificationTitle',
  'notificationCategory',
  'notificationSurahName',
  'notificationPageNumber',
  'notificationAlert',
  'notificationNameLabel',
  'addNotificationAction',
  'alarm_specific_date',
];

// قاموس الترجمة لكل لغة (reminders + المفاتيح الـ18)
const t = {
  id: {
    reminders: 'Pengingat',
    notificationManagerTitle: 'Pengelola Pengingat',
    addNewNotification: 'Tambah Pengingat Baru',
    notificationType: 'Pengulangan Pengingat',
    notificationTimes: 'Waktu Pengingat',
    notificationSound: 'Suara Pengingat',
    uploadCustomSound: 'Pilih Suara dari Perangkat',
    enableAlarmMode: 'Mode Alarm',
    alarmModeDescription: 'Bunyi akan terus berbunyi sampai dihentikan secara manual.',
    deliveryMethod: 'Metode Pengingat',
    browserNotificationTitle: 'Kirim Pemberitahuan ke Ponsel / Peramban',
    notificationCategory: 'Ingatkan Berdasarkan',
    notificationSurahName: 'Surat',
    notificationPageNumber: 'Halaman',
    notificationAlert: 'Umum',
    notificationNameLabel: 'Nama Pengingat',
    addNotificationAction: 'Simpan Pengingat',
    alarm_specific_date: 'Tanggal Pengingat',
  },
  ms: {
    reminders: 'Peringatan',
    notificationManagerTitle: 'Pengurus Peringatan',
    addNewNotification: 'Tambah Peringatan Baharu',
    notificationType: 'Ulangan Peringatan',
    notificationTimes: 'Waktu Peringatan',
    notificationSound: 'Bunyi Peringatan',
    uploadCustomSound: 'Pilih Bunyi daripada Peranti',
    enableAlarmMode: 'Mod Penggera',
    alarmModeDescription: 'Bunyi akan berterusan sehingga dihentikan secara manual.',
    deliveryMethod: 'Kaedah Peringatan',
    browserNotificationTitle: 'Hantar Pemberitahuan ke Telefon / Pelayar',
    notificationCategory: 'Peringat Mengikut',
    notificationSurahName: 'Surah',
    notificationPageNumber: 'Halaman',
    notificationAlert: 'Am',
    notificationNameLabel: 'Nama Peringatan',
    addNotificationAction: 'Simpan Peringatan',
    alarm_specific_date: 'Tarikh Peringatan',
  },
  ur: {
    reminders: 'یاد دہانیاں',
    notificationManagerTitle: 'یاد دہانی کا انتظام',
    addNewNotification: 'نئی یاد دہانی شامل کریں',
    notificationType: 'یاد دہانی کی تکرار',
    notificationTimes: 'یاد دہانی کے اوقات',
    notificationSound: 'یاد دہانی کی آواز',
    uploadCustomSound: 'آلہ سے آواز منتخب کریں',
    enableAlarmMode: 'الارم موڈ',
    alarmModeDescription: 'رنگنا جاری رہے گا جب تک اسے دستی طور پر بند نہ کیا جائے۔',
    deliveryMethod: 'یاد دہانی کا طریقہ',
    browserNotificationTitle: 'فون / براؤزر کو اطلاع بھیجیں',
    notificationCategory: 'ان کے لحاظ سے یاد دلائیں',
    notificationSurahName: 'سورہ',
    notificationPageNumber: 'صفحہ',
    notificationAlert: 'عام',
    notificationNameLabel: 'یاد دہانی کا نام',
    addNotificationAction: 'یاد دہانی محفوظ کریں',
    alarm_specific_date: 'یاد دہانی کی تاریخ',
  },
  bn: {
    reminders: 'রিমাইন্ডার',
    notificationManagerTitle: 'রিমাইন্ডার ব্যবস্থাপনা',
    addNewNotification: 'নতুন রিমাইন্ডার যোগ করুন',
    notificationType: 'রিমাইন্ডার পুনরাবৃত্তি',
    notificationTimes: 'রিমাইন্ডারের সময়',
    notificationSound: 'রিমাইন্ডারের শব্দ',
    uploadCustomSound: 'ডিভাইস থেকে শব্দ নির্বাচন করুন',
    enableAlarmMode: 'অ্যালার্ম মোড',
    alarmModeDescription: 'ম্যানুয়ালি বন্ধ না করা পর্যন্ত রিং হতে থাকবে।',
    deliveryMethod: 'রিমাইন্ডারের পদ্ধতি',
    browserNotificationTitle: 'ফোন / ব্রাউজারে বিজ্ঞপ্তি পাঠান',
    notificationCategory: 'অনুযায়ী মনে করিয়ে দিন',
    notificationSurahName: 'সূরা',
    notificationPageNumber: 'পৃষ্ঠা',
    notificationAlert: 'সাধারণ',
    notificationNameLabel: 'রিমাইন্ডারের নাম',
    addNotificationAction: 'রিমাইন্ডার সংরক্ষণ করুন',
    alarm_specific_date: 'রিমাইন্ডারের তারিখ',
  },
  tr: {
    reminders: 'Hatırlatmalar',
    notificationManagerTitle: 'Hatırlatıcı Yöneticisi',
    addNewNotification: 'Yeni Hatırlatıcı Ekle',
    notificationType: 'Hatırlatma Tekrarı',
    notificationTimes: 'Hatırlatma Saatleri',
    notificationSound: 'Hatırlatma Sesi',
    uploadCustomSound: 'Cihazdan Ses Seç',
    enableAlarmMode: 'Alarm Modu',
    alarmModeDescription: 'El ile durdurulana kadar çalmaya devam edecek.',
    deliveryMethod: 'Hatırlatma Yöntemi',
    browserNotificationTitle: 'Telefon / Tarayıcıya Bildirim Gönder',
    notificationCategory: 'Hatırlatma Ölçütü',
    notificationSurahName: 'Sure',
    notificationPageNumber: 'Sayfa',
    notificationAlert: 'Genel',
    notificationNameLabel: 'Hatırlatıcı Adı',
    addNotificationAction: 'Hatırlatıcıyı Kaydet',
    alarm_specific_date: 'Hatırlatma Tarihi',
  },
  fa: {
    reminders: 'یادآوری‌ها',
    notificationManagerTitle: 'مدیریت یادآوری‌ها',
    addNewNotification: 'افزودن یادآوری جدید',
    notificationType: 'تکرار یادآوری',
    notificationTimes: 'زمان‌های یادآوری',
    notificationSound: 'صدای یادآوری',
    uploadCustomSound: 'انتخاب صدا از دستگاه',
    enableAlarmMode: 'حالت هشدار',
    alarmModeDescription: 'زنگ تا زمانی که به‌صورت دستی متوقف شود ادامه می‌یابد.',
    deliveryMethod: 'روش یادآوری',
    browserNotificationTitle: 'ارسال اعلان به تلفن / مرورگر',
    notificationCategory: 'یادآوری بر اساس',
    notificationSurahName: 'سوره',
    notificationPageNumber: 'صفحه',
    notificationAlert: 'عمومی',
    notificationNameLabel: 'نام یادآوری',
    addNotificationAction: 'ذخیره یادآوری',
    alarm_specific_date: 'تاریخ یادآوری',
  },
  ha: {
    reminders: 'Tunatarwa',
    notificationManagerTitle: 'Gudanar da Tunatarwa',
    addNewNotification: 'Ƙara Sabuwar Tunatarwa',
    notificationType: 'Maimaita Tunatarwa',
    notificationTimes: 'Lokutan Tunatarwa',
    notificationSound: 'Sautin Tunatarwa',
    uploadCustomSound: 'Zaɓi Sauti daga Na\'urar',
    enableAlarmMode: 'Yanayin Ƙararrawa',
    alarmModeDescription: 'Sauti zai ci gaba da yin saj har sai a daka shi da hannu.',
    deliveryMethod: 'Hanyar Tunatarwa',
    browserNotificationTitle: 'Aika Sanarwa zuwa Waya / Browser',
    notificationCategory: 'Tunatar da',
    notificationSurahName: 'Surah',
    notificationPageNumber: 'Shafi',
    notificationAlert: 'Gabaɗaya',
    notificationNameLabel: 'Sunan Tunatarwa',
    addNotificationAction: 'Ajiye Tunatarwa',
    alarm_specific_date: 'Kwanan Watan Tunatarwa',
  },
  fr: {
    reminders: 'Rappels',
    notificationManagerTitle: 'Gestionnaire de Rappels',
    addNewNotification: 'Ajouter un Nouveau Rappel',
    notificationType: 'Répétition du Rappel',
    notificationTimes: 'Heures du Rappel',
    notificationSound: 'Son du Rappel',
    uploadCustomSound: 'Choisir un Son depuis l\'Appareil',
    enableAlarmMode: 'Mode Alarme',
    alarmModeDescription: 'La sonnerie continuera jusqu\'à l\'arrêt manuel.',
    deliveryMethod: 'Méthode du Rappel',
    browserNotificationTitle: 'Envoyer une Notification au Téléphone / Navigateur',
    notificationCategory: 'Rappeler Par',
    notificationSurahName: 'Sourate',
    notificationPageNumber: 'Page',
    notificationAlert: 'Général',
    notificationNameLabel: 'Nom du Rappel',
    addNotificationAction: 'Enregistrer le Rappel',
    alarm_specific_date: 'Date du Rappel',
  },
  es: {
    reminders: 'Recordatorios',
    notificationManagerTitle: 'Gestor de Recordatorios',
    addNewNotification: 'Añadir Nuevo Recordatorio',
    notificationType: 'Repetición del Recordatorio',
    notificationTimes: 'Horarios del Recordatorio',
    notificationSound: 'Sonido del Recordatorio',
    uploadCustomSound: 'Elegir Sonido del Dispositivo',
    enableAlarmMode: 'Modo Alarma',
    alarmModeDescription: 'El timbre continuará hasta que se detenga manualmente.',
    deliveryMethod: 'Método del Recordatorio',
    browserNotificationTitle: 'Enviar Notificación al Teléfono / Navegador',
    notificationCategory: 'Recordar Por',
    notificationSurahName: 'Sura',
    notificationPageNumber: 'Página',
    notificationAlert: 'General',
    notificationNameLabel: 'Nombre del Recordatorio',
    addNotificationAction: 'Guardar Recordatorio',
    alarm_specific_date: 'Fecha del Recordatorio',
  },
  de: {
    reminders: 'Erinnerungen',
    notificationManagerTitle: 'Erinnerungsverwaltung',
    addNewNotification: 'Neue Erinnerung Hinzufügen',
    notificationType: 'Erinnerungswiederholung',
    notificationTimes: 'Erinnerungszeiten',
    notificationSound: 'Erinnerungston',
    uploadCustomSound: 'Ton vom Gerät Auswählen',
    enableAlarmMode: 'Alarmmodus',
    alarmModeDescription: 'Das Klingeln wird fortgesetzt, bis es manuell gestoppt wird.',
    deliveryMethod: 'Erinnerungsmethode',
    browserNotificationTitle: 'Benachrichtigung an Telefon / Browser Senden',
    notificationCategory: 'Erinnern Nach',
    notificationSurahName: 'Sure',
    notificationPageNumber: 'Seite',
    notificationAlert: 'Allgemein',
    notificationNameLabel: 'Name der Erinnerung',
    addNotificationAction: 'Erinnerung Speichern',
    alarm_specific_date: 'Datum der Erinnerung',
  },
  ru: {
    reminders: 'Напоминания',
    notificationManagerTitle: 'Управление Напоминаниями',
    addNewNotification: 'Добавить Новое Напоминание',
    notificationType: 'Повтор Напоминания',
    notificationTimes: 'Время Напоминаний',
    notificationSound: 'Звук Напоминания',
    uploadCustomSound: 'Выбрать Звук с Устройства',
    enableAlarmMode: 'Режим Будильника',
    alarmModeDescription: 'Звонок продолжится до тех пор, пока не будет остановлен вручную.',
    deliveryMethod: 'Способ Напоминания',
    browserNotificationTitle: 'Отправить Уведомление на Телефон / Браузер',
    notificationCategory: 'Напомнить По',
    notificationSurahName: 'Сура',
    notificationPageNumber: 'Страница',
    notificationAlert: 'Общее',
    notificationNameLabel: 'Название Напоминания',
    addNotificationAction: 'Сохранить Напоминание',
    alarm_specific_date: 'Дата Напоминания',
  },
  sw: {
    reminders: 'Vikumbusho',
    notificationManagerTitle: 'Meneja wa Vikumbusho',
    addNewNotification: 'Ongeza Kikumbusho Kipya',
    notificationType: 'Marudio ya Kikumbusho',
    notificationTimes: 'Nyakati za Kikumbusho',
    notificationSound: 'Sauti ya Kikumbusho',
    uploadCustomSound: 'Chagua Sauti kutoka Kifaa',
    enableAlarmMode: 'Hali ya Kengele',
    alarmModeDescription: 'Mlio utaendelea hadi usimamishwe kwa mkono.',
    deliveryMethod: 'Njia ya Kikumbusho',
    browserNotificationTitle: 'Tuma Arifa kwa Simu / Kivinjari',
    notificationCategory: 'Kumbusha Kwa',
    notificationSurahName: 'Surah',
    notificationPageNumber: 'Ukurasa',
    notificationAlert: 'Jumla',
    notificationNameLabel: 'Jina la Kikumbusho',
    addNotificationAction: 'Hifadhi Kikumbusho',
    alarm_specific_date: 'Tarehe ya Kikumbusho',
  },
  zh: {
    reminders: '提醒事项',
    notificationManagerTitle: '提醒管理',
    addNewNotification: '添加新提醒',
    notificationType: '提醒重复',
    notificationTimes: '提醒时间',
    notificationSound: '提醒铃声',
    uploadCustomSound: '从设备选择铃声',
    enableAlarmMode: '闹钟模式',
    alarmModeDescription: '铃声将持续响起，直到手动停止。',
    deliveryMethod: '提醒方式',
    browserNotificationTitle: '向手机 / 浏览器发送通知',
    notificationCategory: '提醒依据',
    notificationSurahName: '古兰经',
    notificationPageNumber: '页',
    notificationAlert: '通用',
    notificationNameLabel: '提醒名称',
    addNotificationAction: '保存提醒',
    alarm_specific_date: '提醒日期',
  },
  ko: {
    reminders: '알림',
    notificationManagerTitle: '알림 관리',
    addNewNotification: '새 알림 추가',
    notificationType: '알림 반복',
    notificationTimes: '알림 시간',
    notificationSound: '알림 소리',
    uploadCustomSound: '기기에서 소리 선택',
    enableAlarmMode: '알람 모드',
    alarmModeDescription: '수동으로 중지할 때까지 벨소리가 계속됩니다.',
    deliveryMethod: '알림 방법',
    browserNotificationTitle: '휴대폰 / 브라우저로 알림 보내기',
    notificationCategory: '알림 기준',
    notificationSurahName: '수라',
    notificationPageNumber: '페이지',
    notificationAlert: '일반',
    notificationNameLabel: '알림 이름',
    addNotificationAction: '알림 저장',
    alarm_specific_date: '알림 날짜',
  },
  ja: {
    reminders: 'リマインダー',
    notificationManagerTitle: 'リマインダー管理',
    addNewNotification: '新しいリマインダーを追加',
    notificationType: 'リマインダーの繰り返し',
    notificationTimes: 'リマインダーの時刻',
    notificationSound: 'リマインダーの音',
    uploadCustomSound: 'デバイスから音を選択',
    enableAlarmMode: 'アラームモード',
    alarmModeDescription: '手動で停止するまで鳴り続けます。',
    deliveryMethod: 'リマインダーの方法',
    browserNotificationTitle: '電話 / ブラウザに通知を送信',
    notificationCategory: 'リマインダーの基準',
    notificationSurahName: 'スーラ',
    notificationPageNumber: 'ページ',
    notificationAlert: '一般',
    notificationNameLabel: 'リマインダー名',
    addNotificationAction: 'リマインダーを保存',
    alarm_specific_date: 'リマインダーの日付',
  },
  bs: {
    reminders: 'Podsjetnici',
    notificationManagerTitle: 'Upravljanje Podsjetnicima',
    addNewNotification: 'Dodaj Novi Podsjetnik',
    notificationType: 'Ponavljanje Podsjetnika',
    notificationTimes: 'Vremena Podsjetnika',
    notificationSound: 'Zvuk Podsjetnika',
    uploadCustomSound: 'Odaberi Zvuk sa Uređaja',
    enableAlarmMode: 'Mod Alarma',
    alarmModeDescription: 'Zvono će nastaviti dok se ručno ne zaustavi.',
    deliveryMethod: 'Način Podsjetnika',
    browserNotificationTitle: 'Pošalji Obavještenje na Telefon / Pregledač',
    notificationCategory: 'Podsjeti Po',
    notificationSurahName: 'Sura',
    notificationPageNumber: 'Stranica',
    notificationAlert: 'Opšte',
    notificationNameLabel: 'Naziv Podsjetnika',
    addNotificationAction: 'Sačuvaj Podsjetnik',
    alarm_specific_date: 'Datum Podsjetnika',
  },
  sq: {
    reminders: 'Kujtuesit',
    notificationManagerTitle: 'Menaxhimi i Kujtuesve',
    addNewNotification: 'Shto Kujtues të Ri',
    notificationType: 'Përsëritja e Kujtuesit',
    notificationTimes: 'Kohët e Kujtuesit',
    notificationSound: 'Tingulli i Kujtuesit',
    uploadCustomSound: 'Zgjidh Tingull nga Pajisja',
    enableAlarmMode: 'Mënyra e Alarmit',
    alarmModeDescription: 'Bilbili do të vazhdojë derisa të ndalet manualisht.',
    deliveryMethod: 'Mënyra e Kujtuesit',
    browserNotificationTitle: 'Dërgo Njoftim në Telefon / Shfletues',
    notificationCategory: 'Kujto Sipas',
    notificationSurahName: 'Sureja',
    notificationPageNumber: 'Faqja',
    notificationAlert: 'Përgjithshme',
    notificationNameLabel: 'Emri i Kujtuesit',
    addNotificationAction: 'Ruaj Kujtuesin',
    alarm_specific_date: 'Data e Kujtuesit',
  },
  uz: {
    reminders: 'Eslatmalar',
    notificationManagerTitle: 'Eslatmalarni Boshqarish',
    addNewNotification: 'Yangi Eslatma Qo\'shish',
    notificationType: 'Eslatma Takrori',
    notificationTimes: 'Eslatma Vaqtlari',
    notificationSound: 'Eslatma Ovozi',
    uploadCustomSound: 'Qurilmadan Ovoz Tanlash',
    enableAlarmMode: 'Signal Rejimi',
    alarmModeDescription: 'Signal qo\'lda to\'xtatilmaguncha davom etadi.',
    deliveryMethod: 'Eslatma Usuli',
    browserNotificationTitle: 'Telefon / Brauzerga Xabar Yuborish',
    notificationCategory: 'Eslatish Mezonlari',
    notificationSurahName: 'Sura',
    notificationPageNumber: 'Sahifa',
    notificationAlert: 'Umumiy',
    notificationNameLabel: 'Eslatma Nomi',
    addNotificationAction: 'Eslatmani Saqlash',
    alarm_specific_date: 'Eslatma Sanasi',
  },
  kk: {
    reminders: 'Еске салулар',
    notificationManagerTitle: 'Еске салуларды Басқару',
    addNewNotification: 'Жаңа Еске Салуды Қосу',
    notificationType: 'Еске Салуды Қайталау',
    notificationTimes: 'Еске Салулар Уақыты',
    notificationSound: 'Еске Салудың Дыбысы',
    uploadCustomSound: 'Құрылғыдан Дыбыс Таңдау',
    enableAlarmMode: 'Дабыл Режимі',
    alarmModeDescription: 'Дыбыс қолмен тоқтатылғанға дейін жалғаса береді.',
    deliveryMethod: 'Еске Салу Тәсілі',
    browserNotificationTitle: 'Телефон / Браузерге Хабарлама Жіберу',
    notificationCategory: 'Мынау Бойынша Еске Салу',
    notificationSurahName: 'Сүре',
    notificationPageNumber: 'Бет',
    notificationAlert: 'Жалпы',
    notificationNameLabel: 'Еске Салудың Атауы',
    addNotificationAction: 'Еске Салуды Сақтау',
    alarm_specific_date: 'Еске Салудың Күні',
  },
  ku: {
    reminders: 'Bîrxatbir',
    notificationManagerTitle: 'Rêveberiya Bîrxatbiran',
    addNewNotification: 'Bîrxatbira Nû Lê Zêde Bike',
    notificationType: 'Dubarekirina Bîrxatbirê',
    notificationTimes: 'Demên Bîrxatbirê',
    notificationSound: 'Dengê Bîrxatbirê',
    uploadCustomSound: 'Dengê ji Cîhazê Hilbijêre',
    enableAlarmMode: 'Rewşa Alarmê',
    alarmModeDescription: 'Zengil heya ku bi destê xwe were rawestandin didome.',
    deliveryMethod: 'Rêbaza Bîrxatbirê',
    browserNotificationTitle: 'Agahdarî bi Telefon / Gerokê re bişîne',
    notificationCategory: 'Li Gorî Bîrxat bike',
    notificationSurahName: 'Sûre',
    notificationPageNumber: 'Rûpel',
    notificationAlert: 'Giştî',
    notificationNameLabel: 'Navê Bîrxatbirê',
    addNotificationAction: 'Bîrxatbirê Tomar Bike',
    alarm_specific_date: 'Dîroka Bîrxatbirê',
  },
  vi: {
    reminders: 'Lời Nhắc',
    notificationManagerTitle: 'Quản Lý Lời Nhắc',
    addNewNotification: 'Thêm Lời Nhắc Mới',
    notificationType: 'Lặp Lại Lời Nhắc',
    notificationTimes: 'Thời Gian Nhắc',
    notificationSound: 'Âm Thanh Nhắc',
    uploadCustomSound: 'Chọn Âm Thanh từ Thiết Bị',
    enableAlarmMode: 'Chế Độ Báo Thức',
    alarmModeDescription: 'Âm thanh sẽ tiếp tục cho đến khi được dừng thủ công.',
    deliveryMethod: 'Phương Thức Nhắc',
    browserNotificationTitle: 'Gửi Thông Báo đến Điện Thoại / Trình Duyệt',
    notificationCategory: 'Nhắc Theo',
    notificationSurahName: 'Surah',
    notificationPageNumber: 'Trang',
    notificationAlert: 'Chung',
    notificationNameLabel: 'Tên Lời Nhắc',
    addNotificationAction: 'Lưu Lời Nhắc',
    alarm_specific_date: 'Ngày Nhắc',
  },
  tl: {
    reminders: 'Mga Paalala',
    notificationManagerTitle: 'Pamamahala ng mga Paalala',
    addNewNotification: 'Magdagdag ng Bagong Paalala',
    notificationType: 'Pag-uulit ng Paalala',
    notificationTimes: 'Mga Oras ng Paalala',
    notificationSound: 'Tunog ng Paalala',
    uploadCustomSound: 'Pumili ng Tunog mula sa Device',
    enableAlarmMode: 'Alarm Mode',
    alarmModeDescription: 'Tatawag ito nang tuluyan hanggang sa ihinto nang mano-mano.',
    deliveryMethod: 'Paraan ng Paalala',
    browserNotificationTitle: 'Magpadala ng Abiso sa Telepono / Browser',
    notificationCategory: 'Paalalahanin Ayon sa',
    notificationSurahName: 'Surah',
    notificationPageNumber: 'Pahina',
    notificationAlert: 'Pangkalahatan',
    notificationNameLabel: 'Pangalan ng Paalala',
    addNotificationAction: 'I-save ang Paalala',
    alarm_specific_date: 'Petsa ng Paalala',
  },
  hi: {
    reminders: 'रिमाइंडर',
    notificationManagerTitle: 'रिमाइंडर प्रबंधन',
    addNewNotification: 'नया रिमाइंडर जोड़ें',
    notificationType: 'रिमाइंडर दोहराव',
    notificationTimes: 'रिमाइंडर समय',
    notificationSound: 'रिमाइंडर ध्वनि',
    uploadCustomSound: 'डिवाइस से ध्वनि चुनें',
    enableAlarmMode: 'अलार्म मोड',
    alarmModeDescription: 'जब तक हाथ से रोका न जाए तब तक बजता रहेगा।',
    deliveryMethod: 'रिमाइंडर विधि',
    browserNotificationTitle: 'फ़ोन / ब्राउज़र पर सूचना भेजें',
    notificationCategory: 'इनके अनुसार याद दिलाएँ',
    notificationSurahName: 'सूरह',
    notificationPageNumber: 'पृष्ठ',
    notificationAlert: 'सामान्य',
    notificationNameLabel: 'रिमाइंडर नाम',
    addNotificationAction: 'रिमाइंडर सहेजें',
    alarm_specific_date: 'रिमाइंडर तिथि',
  },
  ta: {
    reminders: 'நினைவூட்டல்கள்',
    notificationManagerTitle: 'நினைவூட்டல் மேலாண்மை',
    addNewNotification: 'புதிய நினைவூட்டலைச் சேர்க்க',
    notificationType: 'நினைவூட்டல் மீண்டும்',
    notificationTimes: 'நினைவூட்டல் நேரங்கள்',
    notificationSound: 'நினைவூட்டல் ஒலி',
    uploadCustomSound: 'சாதனத்திலிருந்து ஒலியைத் தேர்ந்தெடுக்கவும்',
    enableAlarmMode: 'அலாரம் பயன்முறை',
    alarmModeDescription: 'கைமுறையாக நிறுத்தும் வரை ஒலி தொடரும்.',
    deliveryMethod: 'நினைவூட்டல் முறை',
    browserNotificationTitle: 'தொலைபேசி / உலாவிக்கு அறிவிப்பை அனுப்பவும்',
    notificationCategory: 'மூலம் நினைவூட்டவும்',
    notificationSurahName: 'சூரா',
    notificationPageNumber: 'பக்கம்',
    notificationAlert: 'பொது',
    notificationNameLabel: 'நினைவூட்டல் பெயர்',
    addNotificationAction: 'நினைவூட்டலைச் சேமி',
    alarm_specific_date: 'நினைவூட்டல் தேதி',
  },
  si: {
    reminders: 'මතක් කිරීම්',
    notificationManagerTitle: 'මතක් කිරීම් කළමනාකරණය',
    addNewNotification: 'නව මතක් කිරීමක් එක් කරන්න',
    notificationType: 'මතක් කිරීමේ පුනරාවර්තනය',
    notificationTimes: 'මතක් කිරීමේ වේලාවන්',
    notificationSound: 'මතක් කිරීමේ ශබ්දය',
    uploadCustomSound: 'උපාංගයෙන් ශබ්දයක් තෝරන්න',
    enableAlarmMode: 'සීනු ආකාරය',
    alarmModeDescription: 'අතින් නතර කරන තුරු නාදය දිගටම පවතී.',
    deliveryMethod: 'මතක් කිරීමේ ක්‍රමය',
    browserNotificationTitle: 'දුරකථනය / බ්‍රවුසරයට දැන්වීමක් යවන්න',
    notificationCategory: 'අනුව මතක් කරන්න',
    notificationSurahName: 'සූරා',
    notificationPageNumber: 'පිටුව',
    notificationAlert: 'සාමාන්‍ය',
    notificationNameLabel: 'මතක් කිරීමේ නම',
    addNotificationAction: 'මතක් කිරීම සුරකින්න',
    alarm_specific_date: 'මතක් කිරීමේ දිනය',
  },
  am: {
    reminders: 'ማስታወሻዎች',
    notificationManagerTitle: 'የማስታወሻዎች አስተዳደር',
    addNewNotification: 'አዲስ ማስታወሻ ይጨምሩ',
    notificationType: 'የማስታወሻ ድግግሞሽ',
    notificationTimes: 'የማስታወሻ ጊዜዎች',
    notificationSound: 'የማስታወሻ ድምፅ',
    uploadCustomSound: 'ከመሣሪያ ድምፅ ይምረጡ',
    enableAlarmMode: 'የማንቂያ ሁነታ',
    alarmModeDescription: 'በእጅ እስኪቆም ድረስ ድምፁ ይቀጥላል።',
    deliveryMethod: 'የማስታወሻ ዘዴ',
    browserNotificationTitle: 'ለስልክ / አሳሽ ማሳወቂያ ይላኩ',
    notificationCategory: 'በሚከተለው አስታውሱ',
    notificationSurahName: 'ሱራ',
    notificationPageNumber: 'ገጽ',
    notificationAlert: 'አጠቃላይ',
    notificationNameLabel: 'የማስታወሻ ስም',
    addNotificationAction: 'ማስታወሻውን ያስቀምጡ',
    alarm_specific_date: 'የማስታወሻ ቀን',
  },
  yo: {
    reminders: 'Ìrántí',
    notificationManagerTitle: 'Ìṣàkóso Ìrántí',
    addNewNotification: 'Ṣ\'àfikún Ìrántí Tuntun',
    notificationType: 'Ìtúnṣe Ìrántí',
    notificationTimes: 'Àkókò Ìrántí',
    notificationSound: 'Ohun Ìrántí',
    uploadCustomSound: 'Yan Ohun láti inú Ẹrọ',
    enableAlarmMode: 'Àwọn Ìkilo',
    alarmModeDescription: 'Ohun náà yóò tèlé títí di ohun tí a fi ọwọ́ pa.',
    deliveryMethod: 'Ọnà Ìrántí',
    browserNotificationTitle: 'Fi Ìfitónilétì ránṣẹ́ sí Fóònù / Awújo',
    notificationCategory: 'Rántí Nipa',
    notificationSurahName: 'Surah',
    notificationPageNumber: 'Oju-iwe',
    notificationAlert: 'Gbogbogbo',
    notificationNameLabel: 'Orúkọ Ìrántí',
    addNotificationAction: 'Fi Ìrántí Pamọ́',
    alarm_specific_date: 'Déètì Ìrántí',
  },
  om: {
    reminders: 'Gorsa',
    notificationManagerTitle: 'Bulchiinsa Gorsaa',
    addNewNotification: 'Gorsa Haaraa Dabali',
    notificationType: 'Irra-deebi\'iinsa Gorsaa',
    notificationTimes: 'Yeroo Gorsaa',
    notificationSound: 'Sagalee Gorsaa',
    uploadCustomSound: 'Qabiyyee irraa Sagalee Filadhu',
    enableAlarmMode: 'Haala Alaarmaa',
    alarmModeDescription: 'Sagaleen hanga harkaan dhaabfamutti itti fufa.',
    deliveryMethod: 'Karaa Gorsaa',
    browserNotificationTitle: 'Beeksisa Bilbila / Biraawuziitti Ergi',
    notificationCategory: 'Akkaataa Itti Gorsan',
    notificationSurahName: 'Suuraa',
    notificationPageNumber: 'Fuula',
    notificationAlert: 'Waliigalaa',
    notificationNameLabel: 'Maqaa Gorsaa',
    addNotificationAction: 'Gorsaa Olkaa\'i',
    alarm_specific_date: 'Guyyaa Gorsaa',
  },
};

function reindent(text) {
  // JSON.stringify بـ مسافتين لإبقاء التنسيق الأصلي
  return JSON.stringify(text, null, 2) + '\n';
}

const report = [];
let totalFiles = 0;
let totalChanged = 0;

for (const [lang, dict] of Object.entries(t)) {
  const file = path.join(dir, lang + '.json');
  if (!fs.existsSync(file)) {
    report.push(`[نفذ] ${lang}: الملف غير موجود`);
    continue;
  }
  totalFiles++;
  const raw = fs.readFileSync(file, 'utf8');
  let data;
  try {
    data = JSON.parse(raw);
  } catch (e) {
    report.push(`[خطأ] ${lang}: JSON غير صالح قبل التعديل — ${e.message}`);
    continue;
  }

  let changed = 0;
  const missing = [];

  // إضافة reminders بعد notifications مباشرة (مع الحفاظ على الترتيب)
  if ('notifications' in data && !('reminders' in data)) {
    const keysOrdered = Object.keys(data);
    const newData = {};
    for (const k of keysOrdered) {
      newData[k] = data[k];
      if (k === 'notifications') {
        newData['reminders'] = dict.reminders;
        changed++;
      }
    }
    data = newData;
  } else if (!('reminders' in data)) {
    // لا يوجد مفتاح notifications — أضف reminders في النهاية
    data['reminders'] = dict.reminders;
    changed++;
  }

  // تحديث المفاتيح الـ18
  for (const key of keys) {
    if (key in data) {
      if (data[key] !== dict[key]) {
        data[key] = dict[key];
        changed++;
      }
    } else {
      missing.push(key);
    }
  }

  if (changed > 0) {
    const out = reindent(data);
    fs.writeFileSync(file, out, 'utf8');
    // تحقق من السلامة بعد الكتابة
    try {
      JSON.parse(fs.readFileSync(file, 'utf8'));
    } catch (e) {
      report.push(`[خطأ حرج] ${lang}: JSON فسد بعد الكتابة — ${e.message}`);
      continue;
    }
    totalChanged += changed;
    report.push(`[تم] ${lang}: ${changed} تغيير${missing.length ? ' — مفقود: ' + missing.join(', ') : ''}`);
  } else {
    report.push(`[بدون تغيير] ${lang}${missing.length ? ' — مفقود: ' + missing.join(', ') : ''}`);
  }
}

console.log('═══════════════════════════════════════');
console.log('تقرير ترجمة التذكيرات');
console.log('═══════════════════════════════════════');
console.log(report.join('\n'));
console.log('═══════════════════════════════════════');
console.log(`إجمالي الملفات: ${totalFiles} | إجمالي التغييرات: ${totalChanged}`);
